ROOT:
    DEV: ~
    WEB: ~
    BAK: ~
TEMPLATES_DIR: templates
PAGE_EXT: md
IMAGE_EXT:
    - jpg
    - jpeg
    - png
PLUGIN_PATHS:
    SYS:
        CONTENT: "/home/charlotte/Webdesign/barely/barely/plugins/content"
        BACKUP: "/home/charlotte/Webdesign/barely/barely/plugins/backup"
        PUBLICATION: "/home/charlotte/Webdesign/barely/barely/plugins/publication"
    USER:
        CONTENT: "/home/charlotte/Webdesign/barely/barely/plugins/content"
        BACKUP: "/home/charlotte/Webdesign/barely/barely/plugins/backup"
        PUBLICATION: "/home/charlotte/Webdesign/barely/barely/plugins/publication"
