ROOT:
    DEV: ~
    WEB: ~
    BAK: ~
PAGE_EXT: md
IMAGE_EXT:
    - jpg
    - jpeg
    - png
FILETYPES:
    RENDERABLE:
            - .md
    COMPRESSABLE:
        IMAGES:
            - .jpg
            - .jpeg
            - .png
        JS:
            - .js
        CSS:
            - .sass
            - .scss
            - .css
    IGNORE:
        - .temp

BACKUP:
    MAX: 10

IMAGES:
    QUALITY: 70
    LONG_SIDE: 1920
    EXTENSIONS:
        - .jpg
        - .jpeg
        - .png
