ROOT:
    DEV: /home/charlotte/Webdesign/barely/blueprints/devroot/
    WEB: /home/charlotte/Webdesign/barely/blueprints/webroot/
    BAK: /home/charlotte/Webdesign/barely/blueprints/backups/

FILETYPES:
    RENDERABLE:
        - .md
    COMPRESSABLE:
        IMAGES:
            - .jpg
            - .jpeg
            - .png
        JS:
            - .js
        CSS:
            - .sass
            - .scss
    IGNORE:
        - .temp

BACKUP:
    MAX: 10
